### ISSUE TITLE
Refresh(true) blocks forever

### ISSUE THREAD

**Issue by moredure** [rs/dnscache#10]
Looks like I found the root cause

**Comment by mikefaraponov** [comment]
https://github.com/rs/dnscache/blob/master/dnscache.go#L79 eash time when refresh is called its trying to make dns resolution of each cacheEntry in the list. Is it expected behaiviour?

**Comment by mikefaraponov** [comment]
When those dns entries over 100k, it hangs)

**Comment by rs** [comment]
That's the purpose of `Refresh`, it refreshes the result of the cached entries.

**Comment by mikefaraponov** [comment]
I think you need to provide ability to refresh (clean list of unused dns entries, some kind of mark and sweep) without dns resolution (at least I am searching for such a solution)

**Comment by mikefaraponov** [comment]
I think that I can provide such a pull request if you are interested in, of course

**Comment by rs** [comment]
sure

**Comment by mikefaraponov** [comment]
Please review https://github.com/rs/dnscache/pull/11
I will be happy to hear any proposal/comments/recommendations

**Comment by mikefaraponov** [comment]
Also I have some ideas make it more like https://github.com/patrickmn/go-cache with ability to set janitor (refresh interval/ mark and sweep interval)
