### ISSUE TITLE
No need to update cache entries with lookup error

### ISSUE THREAD

**Issue by hongshibao** [rs/dnscache#12]
Is it more reasonable that we skip cache entry update (so it keeps using old cached one) if there is error returned from lookupFunc for that entry during Refresh ?

**Comment by sagarkrkv** [comment]
@rs will you be willing to accept a PR to make this configurable? This has become an issue for us in production, even if there's a DNS outage for 100ms, the affect lasts till 60s(our refresh interval).

**Comment by 101glover** [comment]
+1 This would be nice. Not complaining though, thanks for making this repo available.

**Comment by rs** [comment]
I can certainly accept PR. To be noted that I created this lib for someone else and never really used it, so I'm not really an active maintainer. I can certainly review code and merge PR tho.

**Comment by volvofixthis** [comment]
Can you merge this?
